# Generated by Django 3.2.4 on 2021-10-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author_name', models.CharField(max_length=150)),
                ('author_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('New', 'New'), ('Moderated', 'Moderated')], default='New', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
