# Generated by Django 3.2.8 on 2021-10-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': [('view_not_moderated_quotes', 'can view not moderated quotes')]},
        ),
    ]
